### ISSUE TITLE
vs is case sensitive

### ISSUE THREAD

**Issue by fatrobin72** [loopywolf/discordbot#1]
I think it could be made case insensitive by changing line:
`if( parameters[1]!="v" && parameters[1]!="vs") {`
located here: https://github.com/loopywolf/discordbot/blob/master/bot.js#L876
to
`if( parameters[1].toLowerCase()!="v" && parameters[1].toLowerCase()!="vs") {`

Just a small quality of life feature ;)

**Comment by jasonterlecki** [comment]
Resolved.
`var parameters = s.split(/(vs|v)/i);`
